/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2rMX8mki3q5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import {safety_monitor} from "./safety_monitor"
import * as React from "react"


export function homepage() {
  const handleButtonClick = () => {
    safety_monitor();
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-background text-foreground">
      <main className="container px-4 py-12 space-y-12 md:py-24 lg:py-32">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Hello</h1>
          <p className="text-muted-foreground md:text-xl">Welcome to the community website.</p>
        </div>
        <div className="flex flex-col items-center justify-center gap-6 md:grid md:grid-cols-2 lg:grid-cols-3">
          <button onClick={handleButtonClick}>Safety Monitor</button>
          <Button className="w-full max-w-[200px]">Evacuation</Button>
          <Button className="w-full max-w-[200px]">Historical Data</Button>
        </div>
        <div className="text-center">
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Donate to a Cause
          </Link>
        </div>
      </main>
      <footer className="w-full bg-black text-white py-6 px-4 text-sm">
        <div className="container flex flex-col items-center justify-between gap-4 md:flex-row">
          <nav className="flex gap-4" />
          <p>&copy; 2024 commUnity Inc. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
