/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/g6oLnnf3xJU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Arimo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
// pages/donate
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"

export default function donate() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link href="/" className="flex items-center justify-center" prefetch={false}>
          commUnity
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href= "/monitor" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Monitor
          </Link>
          <Link href="/predictions" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Predictions
          </Link>
          <Link href="/evacuation" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Evacuation
          </Link>
        </nav>
      </header>
      <main className="flex-1 grid gap-12 px-4 md:px-6 py-12 md:py-24">
        <section className="grid gap-6 md:grid-cols-[1fr_1fr] md:gap-12">
          <div className="space-y-4">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Find the Right Charity for You
            </h1>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              Tell us your interests, location, and donation amount, and we will recommend the best charities for your needs.
            </p>
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="interests">Interests</Label>
                {/* <Select id="interests" multiple>
                  <SelectTrigger>
                    <SelectValue placeholder="Select interests" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="education">Education</SelectItem>
                    <SelectItem value="health">Health</SelectItem>
                    <SelectItem value="environment">Environment</SelectItem>
                    <SelectItem value="poverty">Poverty</SelectItem>
                    <SelectItem value="animals">Animals</SelectItem>
                    <SelectItem value="disaster-relief">Disaster Relief</SelectItem>
                  </SelectContent>
                </Select> */}
              </div>
              <div className="grid gap-2">
                <Label htmlFor="location">Location</Label>
                <Input id="location" placeholder="Enter your location" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="amount">Donation Amount</Label>
                <Input id="amount" type="number" placeholder="Enter amount" />
              </div>
              <Button type="submit" className="w-full">
                Get Recommendations
              </Button>
            </form>
          </div>
          <div className="space-y-4">
            <Image
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="Charity Donations"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full"
            />
          </div>
        </section>
        <section className="space-y-6">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Current Global Crises</h2>
            <p className="max-w-[800px] text-muted-foreground md:text-xl">
              These are some of the most pressing global issues right now. Consider donating to help make a difference.
            </p>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
            <Card className="space-y-4">
              <CardHeader>
                <CardTitle>Ukraine Humanitarian Crisis</CardTitle>
                <CardDescription>
                  Provide aid and support to those affected by the ongoing conflict in Ukraine.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <Button variant="outline">Donate Now</Button>
                  <div className="text-muted-foreground text-sm">
                    <span className="font-medium">$1.2M</span> raised
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="space-y-4">
              <CardHeader>
                <CardTitle>Famine in East Africa</CardTitle>
                <CardDescription>
                  Help provide food, water, and medical aid to those affected by the severe drought in East Africa.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <Button variant="outline">Donate Now</Button>
                  <div className="text-muted-foreground text-sm">
                    <span className="font-medium">$850K</span> raised
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="space-y-4">
              <CardHeader>
                <CardTitle>Earthquake in Turkey and Syria</CardTitle>
                <CardDescription>
                  Support rescue and recovery efforts for the devastating earthquake that struck Turkey and Syria.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <Button variant="outline">Donate Now</Button>
                  <div className="text-muted-foreground text-sm">
                    <span className="font-medium">$1.5M</span> raised
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Charity Donations. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="/contact" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </footer>
    </div>
  )
}
